### ISSUE TITLE
A question in Package.json

### ISSUE THREAD

**Issue by anycodes** [serverless-components/tencent-koa#6]
Hi, I found there is a package named "aws-serverless-express"  in Package.json. 
Why not Tencent-Express？

**Comment by tinafangkunding** [comment]
cc @pmuens  please check this issue, thanks!

**Comment by medikoo** [comment]
> Why not Tencent-Express？

Do you mean [tencent-express](https://github.com/serverless-components/tencent-express) ?

This is a different thing. `tencent-express` is a component, like `tencent-koa`, while [aws-serverless-express](https://www.npmjs.com/package/aws-serverless-express) is a generic utility which proxies HTTP server instance, maps incoming API Gateway requests to it, and maps back responses that come out of it for API Gateway.

`aws-serverless-express` is also used in [tencent-express](https://github.com/serverless-components/tencent-express) component, still with difference, that over there its code is copied and pasted into component codebase (here: https://github.com/serverless-components/tencent-express/tree/c2546f232182b6f49bdde44773adae4bdc272bf4/shims)

When configuring `tencent-koa` I decided that maintanance-wise it's better to rely on utility directly instead of copying it.

Still, if for any reason it'll appear that `aws-serverless-express` is not perfectly compliant with Tencent's API Gateway, or that for some other reasons we need to alter it, then definitely we should prepare our own `tencent-serverless-express` which could be altered version of `aws-serverless-express` and rely on that one instead.

**Comment by pmuens** [comment]
Thanks for responding @medikoo :+1:

I just wanted to add that we've also worked on [serverless/express](https://github.com/serverless/express) which is a general express component and could be a drop-in replacement for the `aws-serverless-express` component in the near future.

**Comment by medikoo** [comment]
> I just wanted to add that we've also worked on serverless/express which is a general express component and could be a drop-in replacement for the aws-serverless-express component in the near future. 

This looks more as `tencent-express` component but for AWS, and it also seems to have `aws-serverless-express` copied and pasted here: https://github.com/serverless/express/tree/edbd931b01e59af9fa86cf1b1cebf8877fa9ed9c/src/include.

**Comment by medikoo** [comment]
If for some reason we want to avoid using `aws-serveless-express`. We may create more generic and configurable version of it and publish as `serverless-express`.

Having that we may use it in whatever component that aims to run `express`, `koa` or any other HTTP middleware utility.

**Comment by pmuens** [comment]
My understanding is that the `serverless/express` component should be the generic one in the future. Otherwise, why the renaming to `serverless/express`? I could be wrong, though.

**Comment by medikoo** [comment]
Ok, so you mean that any component for any provider that involves support for HTTP middleware engine, will internally initialize `serverless/express` component (?)

Still in that case name is a bit confusing, as `express` implies it's done for express specifically, while `express` is higher level than `connect` or `koa` (but actually same issue is shared already by `aws-serverless-express`, which also works out of a box with `koa` or `connect`, not specifically just `express`).

**Comment by pmuens** [comment]
> Ok, so you mean that any component for any provider that involves support for HTTP middleware engine, will internally initialize serverless/express component (?)

Yes. That's how I understood it. I agree that the name is confusing in that case.
